name: Trigger Update in Xazy

on:
  push:
    branches:
      - main

jobs:
  trigger_update:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in Xazy repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.MASALA_TOKEN }}" \
            https://api.github.com/repos/XazyProject/xazy/dispatches \
            -d '{"event_type": "masala-updated"}'
