name: Update Masala in Xazy

on:
  repository_dispatch:
    types: [masala-updated]

jobs:
  update_masala:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout masala repository
        uses: actions/checkout@v2
        with:
          repository: XazyProject/masala
          path: masala  # Specify the directory to clone into

      - name: Copy Masala files
        run: |
          cp -r masala/fundamentalebi/* src/masala/
          cp -r masala/sashualoDonisHtmlCss/* src/masala/
          # Add more cp commands as needed for other folders or files
