name: Update Masala in Xazy

on:
  repository_dispatch:
    types: [masala-updated]

jobs:
  update_masala:
    runs-on: ubuntu-latest

    steps:

      - name: Copy Masala files
        run: |
          cp -r ./fundamentalebi/* src/masala/
          cp -r ./sashualoDonisHtmlCss/* src/masala/
          # Add more cp commands as needed for other folders or files
      - name: Debug Token
      - run: echo ${{ secrets.MASALA_TOKEN }}